/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ENABLE_aliases.h"
#include "ENABLE.h"
#include "ADC.h"
#include "pote_PIN_aliases.h"
#include "pote_PIN.h"
#include "SPEED_aliases.h"
#include "SPEED.h"
#include "DIR_aliases.h"
#include "DIR.h"
#include "BRAKEn_aliases.h"
#include "BRAKEn.h"
#include "HA_aliases.h"
#include "HA.h"
#include "HB_aliases.h"
#include "HB.h"
#include "UART.h"
#include "vel_counter_clk.h"
#include "isr_HA.h"
#include "isr_counter.h"
#include "control_clk.h"
#include "vel_control_isr.h"
#include "button_PIN_aliases.h"
#include "button_PIN.h"
#include "isr_button.h"
#include "led_PIN_aliases.h"
#include "led_PIN.h"
#include "ADC_tension.h"
#include "tension_PIN_aliases.h"
#include "tension_PIN.h"
#include "tensor_control_isr.h"
#include "angle_control_isr.h"
#include "DirCounter.h"
#include "control_clk_1.h"
#include "VDAC8_Speed.h"
#include "Timer_ha.h"
#include "RxInt.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "ADC_Bypass_aliases.h"
#include "ADC_Bypass.h"
#include "UART_IntClock.h"
#include "ADC_tension_IRQ.h"
#include "ADC_tension_theACLK.h"
#include "DirCounter_Cnt16.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

