/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PM1_DIR_aliases.h"
#include "PM1_DIR.h"
#include "pote_PIN_aliases.h"
#include "pote_PIN.h"
#include "ADC.h"
#include "PM1_BRAKEn_aliases.h"
#include "PM1_BRAKEn.h"
#include "PM1_ENABLE_aliases.h"
#include "PM1_ENABLE.h"
#include "UART.h"
#include "PM1_input_aliases.h"
#include "PM1_input.h"
#include "COUNT_ISR.h"
#include "SPD_CLOCK_30.h"
#include "SPD_CLOCK_10K.h"
#include "control_clk.h"
#include "SPD_COMMAND_ISR.h"
#include "PM2_SPD_VDAC8.h"
#include "PM2_BRAKEn_aliases.h"
#include "PM2_BRAKEn.h"
#include "PM2_DIR_aliases.h"
#include "PM2_DIR.h"
#include "tension_PIN_aliases.h"
#include "tension_PIN.h"
#include "tensor_control_isr.h"
#include "RVT_COMMAND_ISR.h"
#include "PM1_HA_TIMER.h"
#include "control_clk_1.h"
#include "PM1_SPD_VDAC8.h"
#include "PM1_DirCounter.h"
#include "PM1_DirCounter_PVT.h"
#include "RxInt.h"
#include "ADC_TS.h"
#include "PM2_ENABLE_aliases.h"
#include "PM2_ENABLE.h"
#include "PM2_HA_ISR.h"
#include "PM2_HA_TIMER.h"
#include "PM1_SPEED_aliases.h"
#include "PM1_SPEED.h"
#include "PM2_DirCounter.h"
#include "PM2_DirCounter_PVT.h"
#include "PM2_input_aliases.h"
#include "PM2_input.h"
#include "PM1_HA_ISR.h"
#include "PM2_SPEED_aliases.h"
#include "PM2_SPEED.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "ADC_Bypass_aliases.h"
#include "ADC_Bypass.h"
#include "UART_IntClock.h"
#include "PM1_DirCounter_isr.h"
#include "PM1_DirCounter_Cnt16.h"
#include "ADC_TS_SAR.h"
#include "ADC_TS_IntClock.h"
#include "ADC_TS_TempBuf_dma.h"
#include "ADC_TS_FinalBuf_dma.h"
#include "ADC_TS_IRQ.h"
#include "PM2_DirCounter_isr.h"
#include "PM2_DirCounter_Cnt16.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

